### ISSUE TITLE
[FORGE] Crash when running with CreateTweaker

### ISSUE THREAD

**Issue by Beethoven-n** [UnlikePaladin/paladin-furniture-mod#100]
Simply installing CreateTweaker with PFM on Forge causes an immediate crash.

Forge version: 43.3.0
CreateTweaker version: 3.0.0.6
Paladin's Furniture Mod version: 1.2.0
Minecraft version: 1.19.2

https://mclo.gs/AVzcRSN

**Comment by Unixkitty** [comment]
Same thing with KubeJS it seems. 

Minecraft: 1.19.2
Forge: 43.3.5
Paladin's Furniture: 1.2.0

All I did was put the following into a previously working instance:
kubejs-forge-1902.6.2-build.59.jar
rhino-forge-1902.2.3-build.284.jar
architectury-6.5.90-forge.jar

https://mclo.gs/dFR0B7t

**Comment by UnlikePaladin** [comment]
Both of those are a generic crash, it could be missing dependencies, a different mod or anything really, the stacktrace blames my mod because of a bug in the 1.2 release but it is not the actual cause of the crash, a full game log (the latest.log file for example) would be needed to find the real thing that crashed the game, closing this as invalid but feel free to reopen it with a valid log.
