### ISSUE TITLE
Crash on startup, including 2 other mods with the same issue

### ISSUE THREAD

**Issue by StarrSage** [UnlikePaladin/paladin-furniture-mod#12]
[crash-2022-10-30_17.21.00-fml.txt](https://github.com/UnlikePaladin/paladins-furniture/files/9896846/crash-2022-10-30_17.21.00-fml.txt)

**Comment by UnlikePaladin** [comment]
This is literally the weirdest crash I've ever seen, it seems to be related to the config somehow but it's on Cloth Config's side because it failed to parse because of an extraneous = sign so your config file must be broken or something but this isn't really on my side. If you're still encountering the issue feel free to reopen it.
