### ISSUE TITLE
[Fabric 1.19.2] Would be nice if we could toggle fridge recipes in the config

### ISSUE THREAD

**Issue by vizthex123** [UnlikePaladin/paladin-furniture-mod#26]
As the title say, a config option to disable the recipes made inside of a fridge would be nice.

**Comment by UnlikePaladin** [comment]
Not sure why you would want/need that, like Vanilla recipes, mine are also data driven, `pfm:freezing` is the id
`{
  "type": "pfm:freezing",
  "ingredient": {
    "item": "minecraft:potion"
  },
  "result": "minecraft:snowball"
}
`
That's the snowball recipe for example, you can use a data pack to add or remove recipes at will so if you wanted to remove the snowball recipe for example you'd make a data pack and under the data/recipes directory add a "snowball_recipe.json" that just had 
`
{
}
` 
inside and the game would load it instead of the mod's and therefore the recipe be disabled, so adding this to the config would not only take up a lot of space but also be redundant. I'm closing this for now.

**Comment by vizthex123** [comment]
Of course it uses datapacks.... I just find it vastly easier to have a single config option rather than having to wrestle with loading them into worlds anyone makes (since my packs are public).
