### ISSUE TITLE
[Fabric 1.19.2/0.14.24] Crashes/Loading Errors with latest version

### ISSUE THREAD

**Issue by pokesmells** [UnlikePaladin/paladin-furniture-mod#66]
Hi there.

After updating to the latest release of Paladin's Furniture it seems as though it either permanently freezes when just with itself or crashes when having **Language Reload** on,

When not having Language Reload on, it mainly freezes specifically when doing the resource reload part of loading in.

https://mclo.gs/lLEUW5E

Crash Report with Language Reload on.

There is no crash report when not having it on since it just freezes up as stated before.

**Comment by UnlikePaladin** [comment]
Yeah so I basically load languages and translations early on because I do dynamic block translations and generate them the first time assets are loaded and from a quick glance they seem to be doing some incompatible mixins that modify vanilla code and therefore break my mod's translation system. This one might take a bit to fix I'm afraid, you'll either have to remove Language Reload when playing with my mod or vice versa until I can come up with a good solution. But I'll look into it, thanks for the bug report

**Comment by UnlikePaladin** [comment]
Oh also the freezes you are seeing is probably it generating assets, it only does it the first time you install the mod or if you alter your mods list, on future boots it should no longer happen, just give it a second or two, it shouldn't take that long but if it's taking too long, please open a bug report with a game log with it frozen.

**Comment by pokesmells** [comment]
> Oh also the freezes you are seeing is probably it generating assets, it only does it the first time you install the mod or if you alter your mods list, on future boots it should no longer happen, just give it a second or two, it shouldn't take that long but if it's taking too long, please open a bug report with a game log with it frozen.

I'm aware of this, but I shall make a new report since i waited approximately 10 mins without any response from my output log or presence of a instance loading up.

**Comment by pokesmells** [comment]
Thank you for the response as well.

**Comment by ghost** [comment]
Hello! For your information Paladin's Furniture seems to be working with the latest version of Language Reload (language-reload-1.5.10+1.20.1.jar)
