### ISSUE TITLE
1.19.2 Fabric | Seriously slows down the game startup speed

### ISSUE THREAD

**Issue by MCXiaoqing** [UnlikePaladin/paladin-furniture-mod#85]
My Minecraft takes an extremely long time to load this mod (at least 10 minutes) and sometimes even crashes on the loading screen. I deleted other mods and got the same result after loading them. I do not know why. | Minecraft 1.19.2  | Fabric 0.15.3 | Fabric API 0.77.0 |
Palidin's Furniture 1.2

**Comment by UnlikePaladin** [comment]
Hi, this is a known problem I'm working on, I have an experimental build which attempts to fix it on the mod's discord which you can join, or you can download it directly from here, it'd would be of great help if you could test it, and let me know if it helps at all, because I can't reproduce the issue on my own computer, this is labeled as 1.2.1 but it is not complete yet. [PFM 1.2.1-Experiment](https://cdn.discordapp.com/attachments/930662977294712942/1190120918761082971/paladin-furniture-mod-1.2.1-fabric-mc1.19.jar)

**Comment by MCXiaoqing** [comment]
[Thanks](https://github.com/UnlikePaladin/paladins-furniture/issues/85#issuecomment-1872466439)

**Comment by MCXiaoqing** [comment]
Seems a little better

**Comment by jefflima1** [comment]
I tested your dev version, in version 1.20.1 it loaded much faster.
