### ISSUE TITLE
Paladins furniture mode causes error

### ISSUE THREAD

**Issue by emmod-190** [UnlikePaladin/paladin-furniture-mod#96]
This mod gives me an error with the fabric api but I cant figure out what it is. I have installed other mods and I dont know if it could be them too but everything is written in the crash report file. How can I solve this problem?

https://mclo.gs/5XjQa4n

**Comment by UnlikePaladin** [comment]
This is an invalid crash log, there's a bug in 1.2 which causes the game to blame my mod but in actuality it could be anything, a full game log, like the latest.log file would be required to actually fix this because that is not useful sadly, feel free to reopen the issue with a full game log if you're still experiencing problems
